### ISSUE TITLE
動作環境でインストールの足りないものを教えてください。

### ISSUE THREAD

**Issue by KazukoShikiya** [TakuKobayashi/teacherHack#2]
今、下記エラーで動きません。
インストールで足りてないものが分からないので、教えてください。

C:\workspace\GitHub\teacherHack>sails lift

info: Starting app...

module.js:338
    throw err;
    ^

Error: Cannot find module 'passport'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\kazco\Documents\GitHub\teacherHack\config\ht
tp.js:25:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\kazco\AppData\Roaming\npm\node_modules\sails\node_modules\includ
e-all\index.js:129:29
    at Array.forEach (native)
    at requireAll (C:\Users\kazco\AppData\Roaming\npm\node_modules\sails\node_mo
dules\include-all\index.js:44:9)
    at buildDictionary (C:\Users\kazco\AppData\Roaming\npm\node_modules\sails\no
de_modules\sails-build-dictionary\index.js:68:14)
    at Function.module.exports.aggregate (C:\Users\kazco\AppData\Roaming\npm\nod
e_modules\sails\node_modules\sails-build-dictionary\index.js:190:9)

**Comment by TakuKobayashi** [comment]
ライブラリとかを追加しました。
もう一回、npm installしてください。

**Comment by KazukoShikiya** [comment]
エラー内容は変わりましたが、エラーは消えず…です。

Error: Cannot find module 'bcrypt'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\kazco\Documents\GitHub\teacherHack\config\pa
ssport.js:3:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at C:\Users\kazco\Documents\GitHub\teacherHack\node_modules\include-all\inde
x.js:129:29
    at Array.forEach (native)
    at requireAll (C:\Users\kazco\Documents\GitHub\teacherHack\node_modules\incl
ude-all\index.js:44:9)
    at buildDictionary (C:\Users\kazco\Documents\GitHub\teacherHack\node_modules
\sails\node_modules\sails-build-dictionary\index.js:68:14)
    at Function.module.exports.aggregate (C:\Users\kazco\Documents\GitHub\teache
rHack\node_modules\sails\node_modules\sails-build-dictionary\index.js:190:9)

なので。
npm install bcryptで大丈夫？と思ったけど、ダメで。
これ見る限り、Pythonインストールが必要っぽいのですが、２と３のどちらがよいでしょうか？
（どっちでもいいのかもしれないけど。）

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)

**Comment by KazukoShikiya** [comment]
とりあえず、どうすればいいかは判明しました。

今、仕事場なので、いろいろインストールできないので、
帰ってから、やってみます。

あとでこれをやること。
http://create-something.hatenadiary.jp/entry/2014/07/13/021655
